repos:
#  - repo: https://github.com/pycqa/pylint
#    rev: pylint-2.6.0
#    hooks:
#    -   id: pylint
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
